<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'news_index' => [[], ['_controller' => 'App\\Controller\\NewsController::index'], [], [['text', '/']], [], []],
    'news_item' => [['slug'], ['_controller' => 'App\\Controller\\NewsController::item'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/news']], [], []],
];
