<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAmtHkcO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAmtHkcO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAmtHkcO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAmtHkcO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAmtHkcO\App_KernelDevDebugContainer([
    'container.build_hash' => 'AmtHkcO',
    'container.build_id' => '4762be92',
    'container.build_time' => 1585154572,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAmtHkcO');
